# Generated by Django 3.2.6 on 2021-08-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(unique=True)),
                ('phone_varified', models.BooleanField(default=False)),
                ('kyc_varified', models.BooleanField(default=False)),
                ('user_image_url', models.ImageField(blank=True, null=True, upload_to='static/Document')),
                ('aadhar_card_url', models.ImageField(blank=True, null=True, upload_to='static/Document')),
            ],
        ),
    ]
