# Generated by Django 3.2.6 on 2021-08-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image_url', models.ImageField(blank=True, null=True, upload_to='static/Document')),
                ('aadhar_card_url', models.ImageField(blank=True, null=True, upload_to='static/Document')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='aadhar_card_url',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_image_url',
        ),
        migrations.AddField(
            model_name='users',
            name='kyc_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.documents'),
        ),
    ]
